// <auto-generated />
namespace HeroAndVillains.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class HeroAnd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(HeroAnd));
        
        string IMigrationMetadata.Id
        {
            get { return "202110200250206_HeroAnd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
